version: '3'
services: 
    incubator:
        container_name: incubator_api
        build: .
        ports:
            - "5000:5000"
        volumes: 
            - ./:/app
        links: 
            - postgres
        depends_on: 
            - postgres
        restart: always
        environment: 
            DB_URI: postgres://root:incubator@postgres/incubator
    
    postgres:
        container_name: incubator_postgres
        image: postgres
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: incubator
        volumes: 
            - ./docker/init/db.sh:/docker-entrypoint-initdb.d/initdb.sh 
            - ./docker/postgres:/var/lib/postgresql/data

        restart: always
